dist: trusty
sudo: required
language: c
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
env:
  global:
  - NJOBS=2
  - COMPILER="system"
  # system <=> 4.02.3
  - PARAMCOQ_URL="https://github.com/CohenCyril/paramcoq.git"
  - MULTINOM_URL="https://github.com/math-comp/multinomials.git"
  - MULTINOM_VERSION="5b46e50983ee68dd1b6932e7e4a3bfc1113e7360"
  matrix:
  - COQ_VERSION="8.6.1" MATHCOMP_VERSION="1.6.1" PARAMCOQ_VERSION="8dbf3fc1a0a0e0177eb9d88f6b76b8eb0dc22889"
  - COQ_VERSION="8.5.3" MATHCOMP_VERSION="1.6.1" PARAMCOQ_VERSION="956d77ff6269159be5828fe8235d2e0dfb1b5987"

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- opam config env && eval $(opam config env)
- opam config var root
- opam repo add coq-released https://coq.inria.fr/opam/released || true
- opam update
- opam repo list
- echo -e '\e[33;1mBuilding Coq\e[0m' && echo -en 'travis_fold:start:coq.build\\r'
- travis_wait opam install -j ${NJOBS} -y ocamlfind camlp5 coq.${COQ_VERSION}
- echo -en 'travis_fold:end:coq.build\\r'
- echo -e '\e[33;1mBuilding Mathcomp\e[0m' && echo -en 'travis_fold:start:mathcomp.build\\r'
- opam install -j ${NJOBS} -y -v coq.${COQ_VERSION} coq-mathcomp-field.${MATHCOMP_VERSION}
- echo -en 'travis_fold:end:mathcomp.build\\r'
- opam list
- echo -e '\e[33;1mBuilding Paramcoq\e[0m' && echo -en 'travis_fold:start:paramcoq.build\\r'
# Some branches have no paramcoq dir & paramcoq isn't Coq-version cross-compat.
# if [ ! -d paramcoq ]; then git clone --depth 50 -n ${PARAMCOQ_URL} paramcoq && pushd paramcoq && git checkout ${PARAMCOQ_VERSION} && popd; fi
- git clone --depth 50 -n ${PARAMCOQ_URL} $HOME/paramcoq && pushd $HOME/paramcoq && git checkout ${PARAMCOQ_VERSION} && popd
- pushd $HOME/paramcoq && make -j ${NJOBS} && make install && popd
- echo -en 'travis_fold:end:paramcoq.build\\r'
- echo -e '\e[33;1mBuilding Multinomials\e[0m' && echo -en 'travis_fold:start:multinom.build\\r'
- git clone --depth 50 -n ${MULTINOM_URL} $HOME/multinom && pushd $HOME/multinom && git checkout ${MULTINOM_VERSION} && popd
- pushd $HOME/multinom && make -j ${NJOBS} && make install && popd
- echo -en 'travis_fold:end:multinom.build\\r'

script:
- echo -e '\e[33;1mBuilding CoqEAL\e[0m' && echo -en 'travis_fold:start:coqeal.build\\r'
- pushd theory && make -j ${NJOBS} && popd
- pushd refinements && make -j ${NJOBS} && make Makefile.coq && make -f Makefile.coq -j ${NJOBS} OTHERFLAGS="-R ../theory CoqEAL.theory" all && popd
- echo -en 'travis_fold:end:coqeal.build\\r'
